//
//  DeveloperPreview.swift
//  AirBnb
//
//  Created by Vitor Henrique Barreiro Marinho on 18/06/24.
//

import Foundation

class DeveloperPreview {
    var listings: [Listing] = [
        
        Listing(id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Jonas Lemos",
                ownerImageUrl: "male-profile-photo",
                numberOfBedrooms: 4,
                numberOfBathrooms: 3,
                numberOfGuests: 4,
                numberOfBeds: 4,
                pricePerNight: 567,
                latitude: 25.7850,
                longitude: -80.1936,
                address: "124 Main St",
                city: "Miami",
                state: "Florida",
                title: "Miami Villa",
                rating: 4.86,
                features: [.selfCheckIn, .superhost],
                amenities: [.wifi, .alarmSystem, .balcony , .laundry, .tv],
                type: .ville, 
                imageUrls: ["listing-4","listing-2","listing-3","listing-1"]),
        
        Listing(id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "John Richard",
                ownerImageUrl: "male-profile-photo",
                numberOfBedrooms: 2,
                numberOfBathrooms: 4,
                numberOfGuests: 1,
                numberOfBeds: 5,
                pricePerNight: 800,
                latitude: 25.1250,
                longitude: -80.1236,
                address: "80 New Jersey",
                city: "Miami",
                state: "Florida",
                title: "Miami Villa",
                rating: 4.86,
                features: [.selfCheckIn, .superhost],
                amenities: [.wifi, .alarmSystem, .balcony , .laundry, .tv],
                type: .ville, 
                imageUrls: ["listing-1","listing-2","listing-3","listing-4"]),

        Listing(id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Gabriel Santos",
                ownerImageUrl: "male-profile-photo",
                numberOfBedrooms: 2,
                numberOfBathrooms: 2,
                numberOfGuests: 2,
                numberOfBeds: 2,
                pricePerNight: 700,
                latitude: 25.2434,
                longitude: -21.2344,
                address: "50 White lake",
                city: "Miami",
                state: "Florida",
                title: "Miami Villa",
                rating: 4.86,
                features: [.superhost],
                amenities: [.wifi, .alarmSystem, .balcony , .laundry, .tv, .kitchen],
                type: .ville,
                imageUrls: ["listing-3","listing-1","listing-2","listing-4"]),

        Listing(id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Raul Ribeiro",
                ownerImageUrl: "male-profile-photo",
                numberOfBedrooms: 4,
                numberOfBathrooms: 3,
                numberOfGuests: 4,
                numberOfBeds: 4,
                pricePerNight: 567,
                latitude: 25.7850,
                longitude: -80.1936,
                address: "124 Main St",
                city: "Miami",
                state: "Florida",
                title: "Miami Villa",
                rating: 4.86,
                features: [.selfCheckIn, .superhost],
                amenities: [.wifi, .alarmSystem, .balcony , .laundry, .tv, .kitchen],
                type: .ville,
                imageUrls: ["listing-2","listing-1","listing-3","listing-4"]),

        Listing(id: NSUUID().uuidString,
                ownerUid: NSUUID().uuidString,
                ownerName: "Ana Julia",
                ownerImageUrl: "male-profile-photo",
                numberOfBedrooms: 4,
                numberOfBathrooms: 3,
                numberOfGuests: 4,
                numberOfBeds: 4,
                pricePerNight: 567,
                latitude: 25.7850,
                longitude: -80.1936,
                address: "124 Main St",
                city: "Miami",
                state: "Florida",
                title: "Miami Villa",
                rating: 4.86,
                features: [.selfCheckIn, .superhost],
                amenities: [.wifi, .alarmSystem, .balcony , .laundry, .tv],
                type: .ville,
                imageUrls: ["listing-2","listing-1","listing-3","listing-4"]),
        
        
    ]
}
